### ISSUE TITLE
AttributeError: module 'worldmap' has no attribute 'colormap'

### ISSUE THREAD

**Issue by lennybe** [erdogant/worldmap#3]
y@MacBook-Pro worldmap % python --version
Python 3.8.7
y@MacBook-Pro worldmap % python          
Python 3.8.7 (default, Dec 24 2020, 19:07:18) 
[Clang 12.0.0 (clang-1200.0.32.27)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import worldmap as worldmap
>>> names   = ['zeeland','Overijssel', 'flevoland']
>>> opacity = [0.1, 0.2, 0.6]
>>> cmap    = ['#ff0000'] # Different red accents
>>> out = worldmap.colormap(names,opacity=opacity, cmap='Set1', loadmap='netherlands')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'worldmap' has no attribute 'colormap'

**Comment by DelinQu** [comment]
> y@MacBook-Pro worldmap % python --version Python 3.8.7 y@MacBook-Pro worldmap % python Python 3.8.7 (default, Dec 24 2020, 19:07:18) [Clang 12.0.0 (clang-1200.0.32.27)] on darwin Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import worldmap as worldmap
> > > > names   = ['zeeland','Overijssel', 'flevoland']
> > > > opacity = [0.1, 0.2, 0.6]
> > > > cmap    = ['#ff0000'] # Different red accents
> > > > out = worldmap.colormap(names,opacity=opacity, cmap='Set1', loadmap='netherlands')
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > AttributeError: module 'worldmap' has no attribute 'colormap'

I replaced it with `plot` function and it worked.

**Comment by erdogant** [comment]
You are right. The updates were outdated but are now working again!
